name: cellStyle
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=25.0
  - python=3.11.11
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - albucore==0.0.23
      - albumentations==2.0.4
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - attrs==25.1.0
      - black==25.1.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - clip==1.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - deprecated==1.2.18
      - diffusers==0.32.2
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - filelock==3.17.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - ftfy==6.3.1
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.70.0
      - huggingface-hub==0.29.1
      - humanize==4.12.3
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - invisible-watermark==0.2.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - lazy-loader==0.4
      - lightning==2.5.0.post0
      - lightning-utilities==0.12.0
      - lpips==0.1.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - narwhals==1.28.0
      - networkx==3.4.2
      - nibabel==5.3.2
      - numpy==2.2.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pathspec==0.12.1
      - pillow==11.1.0
      - platformdirs==4.3.6
      - propcache==0.3.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - pudb==2024.1.3
      - pyarrow==19.0.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydeck==0.9.1
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.0.post0
      - pytz==2025.1
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.23.1
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - shellingham==1.5.4
      - simpleitk==2.5.0
      - simsimd==6.2.1
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.42.2
      - stringzilla==3.12.1
      - sympy==1.13.1
      - taming-transformers==0.0.1
      - tenacity==9.0.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - test-tube==0.7.5
      - threadpoolctl==3.5.0
      - tifffile==2025.2.18
      - tokenizers==0.21.0
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.5.0+cu124
      - torch-fidelity==0.3.0
      - torchio==0.20.8
      - torchmetrics==1.6.1
      - torchvision==0.20.0+cu124
      - tornado==6.4.2
      - tqdm==4.67.1
      - transformers==4.49.0
      - triton==3.1.0
      - typer==0.16.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - urwid==2.6.16
      - urwid-readline==0.15.1
      - wandb==0.19.7
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yapf==0.40.1
      - yarl==1.18.3
      - zipp==3.21.0